---
title: "CompetingSims"
author: "Misha Dolmatov"
date: "2023-12-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
library(DTRreg)
library(lme4)
library(geepack)

expit = function(x) exp(x)/(1 + exp(x))
```

```{r test, message = F}
source("RandomEffectsAFT.R")

sim_random_effect2 = function(n){
  #Direct approach
  x <- runif(n, 0, 2)
  z = rnorm(n, mean = 1,sd = 1)
  
  a <- rbinom(n, 1, expit(2 * x +0.5 -z))
  delta <- rbinom(n, 1, expit(-x + 2.5-0.3*z)) #25% censoring rate

  #Generate epsilon
  epsilon = rbinom(n,1,expit(0.1 + x - z))+1 #50% of each cause
  
  
  #Generate groups and random intercepts for each group
  group = sample(50, n, replace = T)
  rand_effects = rnorm(50, mean = 0, sd = 1)
  ind_effects = map_dbl(group, function(x) rand_effects[x])
  
  beta1 <- c(4, 1.5, 2)
  psi1 <- c(-0.2, 0.3)
  h1beta <- model.matrix(~x + z)
  h1psi <- model.matrix(~x)
  T1 <- exp(h1beta[epsilon== 1, ] %*% beta1+ a[epsilon == 1] *h1psi[epsilon ==1, ] %*% psi1 + ind_effects[epsilon ==1]+ rnorm(sum(epsilon == 1),sd = 0.5))

  beta2 <- c(2, -0.5,1)
  psi2<- c(0.4, -0.4)
  h2beta <- model.matrix(~x + z)
  h2psi <- model.matrix(~x)
  T2 <- exp(h2beta[epsilon == 2, ] %*% beta2+ a[epsilon == 2] *h2psi[epsilon ==2, ] %*% psi2 + ind_effects[epsilon ==2] +rnorm(sum(epsilon == 2),sd = 0.5))


  C <- rexp(sum(delta == 0), 1/300)
  Y = rep(0,n)
  Y[epsilon == 1] = T1
  Y[epsilon == 2] = T2
  Y[delta == 0] = C
  
  
  group = as.factor(group)
  data = tibble(x,z,a,delta,group,Y,epsilon)
  psi1 = aft2(data, a~x, delta~x, log(Y)~ x+ a+a:x,1)[c(3,4)]
  psi2 = aft2(data, a~x, delta~x, log(Y)~ x+z+ a+a:x,1)[c(4,5)]
  psi3 = aft2(data, a~x+z, delta~x+z, log(Y)~ x+ a+a:x,1)[c(3,4)]
  psi4 = aft2(data, a~x+z, delta~x+z, log(Y)~ x+z+ a+a:x,1)[c(4,5)]
  
  c(psi1,psi2,psi3,psi4)
}


set.seed(2024)
res_test = t(replicate(200, sim_random_effect2(1000)))

group1 = res_test[,c(1,3,5,7)] 
colnames(group1) = c("1", "2", "3", "4")
group1 = group1 %>% as_tibble() %>% pivot_longer(1:4, names_to = "Scenario")

p.1 = ggplot(data = group1) + geom_boxplot(aes(x= Scenario, y = value)) + geom_hline(yintercept = -0.2, linetype = 2) + labs(y = expression(hat(psi)[1]))

group2 = res_test[,c(1,3,5,7)+1] 
colnames(group2) = c("1", "2", "3", "4")
group2 = group2 %>% as_tibble() %>% pivot_longer(1:4, names_to = "Scenario")

p.2 = ggplot(data = group2) + geom_boxplot(aes(x= Scenario, y = value))+ geom_hline(yintercept = 0.3, linetype = 2)+ labs(y = expression(hat(psi)[2]))

p.3 = ggarrange(p.1, p.2, ncol = 2, nrow = 1)

```



```{r aft with random effects, message = F}
source("RandomEffectsAFT.R")

sim_random_effect = function(n){
  #Direct approach
  x <- runif(n, 0, 2)
  z = rnorm(n, mean = 1,sd = 1)
  
  a <- rbinom(n, 1, expit(2 * x +0.5 -z))
  delta <- rbinom(n, 1, expit(-x + 2.5-0.3*z)) #25% censoring rate

  #Generate epsilon
  epsilon = rbinom(n,1,expit(0.1 + x - z))+1 #50% of each cause
  
  
  #Generate groups and random intercepts for each group
  group = sample(50, n, replace = T)
  rand_effects = rnorm(50, mean = 0, sd = 1)
  ind_effects = map_dbl(group, function(x) rand_effects[x])
  
  beta1 <- c(4, 1.5, 2)
  psi1 <- c(-0.2, 0.3)
  h1beta <- model.matrix(~x + z)
  h1psi <- model.matrix(~x)
  T1 <- exp(h1beta[epsilon== 1, ] %*% beta1+ a[epsilon == 1] *h1psi[epsilon ==1, ] %*% psi1 + ind_effects[epsilon ==1]+ rnorm(sum(epsilon == 1),sd = 0.5))

  beta2 <- c(2, -0.5,1)
  psi2<- c(0.4, -0.4)
  h2beta <- model.matrix(~x + z)
  h2psi <- model.matrix(~x)
  T2 <- exp(h2beta[epsilon == 2, ] %*% beta2+ a[epsilon == 2] *h2psi[epsilon ==2, ] %*% psi2 + ind_effects[epsilon ==2] +rnorm(sum(epsilon == 2),sd = 0.5))


  C <- rexp(sum(delta == 0), 1/300)
  Y = rep(0,n)
  Y[epsilon == 1] = T1
  Y[epsilon == 2] = T2
  Y[delta == 0] = C
  
  
  group = as.factor(group)
  data = tibble(x,z,a,delta,group,Y,epsilon)
  psi1 = aft(data, a~x, delta~x, log(Y)~ x+ a+a:x + (1|group),1)[c(3,4)]
  psi2 = aft(data, a~x, delta~x, log(Y)~ x+z+ a+a:x + (1|group),1)[c(4,5)]
  psi3 = aft(data, a~x+z, delta~x+z, log(Y)~ x+ a+a:x + (1|group),1)[c(3,4)]
  psi4 = aft(data, a~x+z, delta~x+z, log(Y)~ x+z+ a+a:x + (1|group),1)[c(4,5)]
  
  c(psi1,psi2,psi3,psi4)
}


#n = 1000
N = 200
n = 1000

set.seed(2024)
res2 = t(replicate(N, sim_random_effect(n)))

group1 = res2[,c(1,3,5,7)] 
colnames(group1) = c("1", "2", "3", "4")
group1 = group1 %>% as_tibble() %>% pivot_longer(1:4, names_to = "Scenario")

p.1 = ggplot(data = group1) + geom_boxplot(aes(x= Scenario, y = value)) + geom_hline(yintercept = -0.2, linetype = 2) + labs(y = expression(hat(psi)[1]))

group2 = res2[,c(1,3,5,7)+1] 
colnames(group2) = c("1", "2", "3", "4")
group2 = group2 %>% as_tibble() %>% pivot_longer(1:4, names_to = "Scenario")

p.2 = ggplot(data = group2) + geom_boxplot(aes(x= Scenario, y = value))+ geom_hline(yintercept = 0.3, linetype = 2)+ labs(y = expression(hat(psi)[2]))

p.3 = ggarrange(p.1, p.2, ncol = 2, nrow = 1)

setwd("C:/Users/misha/Documents/Thesis/Simulations")

ggsave("param.png", p.3, width=12, height = 6)

```


```{r}
#n=5000
N = 200
n = 10000

set.seed(2024)
res2 = t(replicate(N, sim_random_effect(n)))

group1 = res2[,c(1,3,5,7)] 
colnames(group1) = c("1", "2", "3", "4")
group1 = group1 %>% as_tibble() %>% pivot_longer(1:4, names_to = "Scenario")

p.1 = ggplot(data = group1) + geom_boxplot(aes(x= Scenario, y = value)) + geom_hline(yintercept = -0.2, linetype = 2) + labs(y = expression(hat(psi)[1]))

group2 = res2[,c(1,3,5,7)+1] 
colnames(group2) = c("1", "2", "3", "4")
group2 = group2 %>% as_tibble() %>% pivot_longer(1:4, names_to = "Scenario")

p.2 = ggplot(data = group2) + geom_boxplot(aes(x= Scenario, y = value))+ geom_hline(yintercept = 0.3, linetype = 2)+ labs(y = expression(hat(psi)[2]))

p.3 = ggarrange(p.1, p.2, ncol = 2, nrow = 1)

ggsave("param2.png", p.3, width=12, height = 6)
```


```{r scenario 1, warning=F,fig.width= 10, fig.height=10}

#Scenario 1: Weighted performs the best
#When one cause is more likely, however less likely cause has very negative blips compared to most probable cause
#epsilon = rbinom(n,1,expit(x+0.5))+1

source("RandomEffectsAFT.R")

set.seed(2024)

n_rep = 200
n_test = 500
n_train = 1000

psi1_fixed= c(0.7,-0.5)
psi2_fixed= c(-0.7, -0.5)
  
train = sim_data(n_train, cens = T, psi1_fixed, psi2_fixed)
test = sim_data(n_test, cens = F, psi1_fixed, psi2_fixed)
res = t(replicate(n_rep,sim_stochastic_regime(train[sample(1:n_train, n_train, replace = T),],test, psi1_fixed, psi2_fixed)))

plots1 =plot_results(res, test)

r.1 = plots1[[1]]
colMeans(plots1[[2]])
plots1[[3]]

ggsave("blip1.png", r.1, width=12, height = 12)
```


```{r scenario 2, warning=F, fig.width= 10, fig.height=10}
source("RandomEffectsAFT.R")

#Scenario 3 : Greedy performs the best
#When one cause is more likely and the less likely cause does not have very negative blips
#epsilon = rbinom(n,1,expit(x+0.5))+1
set.seed(2024)

n_rep = 200
n_test = 500
n_train = 1000


psi1_fixed= c(-0.6, -0.7)
psi2_fixed= c(0.1, 0.1)
  
train = sim_data(n_train, cens = T, psi1_fixed, psi2_fixed)
test = sim_data(n_test, cens = F, psi1_fixed, psi2_fixed)
res = t(replicate(n_rep,sim_stochastic_regime(train[sample(1:n_train, n_train, replace = T),],test, psi1_fixed, psi2_fixed)))

plots2 =plot_results(res, test)

r.2 =plots2[[1]]
colMeans(plots2[[2]])
plots2[[3]]

ggsave("blip2.png", r.2, width=12, height = 12)
```

```{r}
source("RandomEffectsAFT.R")

#Scenario 3 : Same slopes -> so one regime always recommends negative, one always recommends positive -> greedy performs worse since crosses 0 for significant portion of group

#epsilon = rbinom(n,1,expit(x+0.5))+1
set.seed(2024)

n_rep = 200
n_test = 500
n_train = 1000


psi1_fixed= c(-0.6, 0.1)
psi2_fixed= c(0.1, 0.1)
  
train = sim_data(n_train, cens = T, psi1_fixed, psi2_fixed)
test = sim_data(n_test, cens = F, psi1_fixed, psi2_fixed)
res = t(replicate(n_rep,sim_stochastic_regime(train[sample(1:n_train, n_train, replace = T),],test, psi1_fixed, psi2_fixed)))

plots2 =plot_results(res, test)

r.2 =plots2[[1]]
colMeans(plots2[[2]])
plots2[[3]]

ggsave("blip3.png", r.2, width=12, height = 12)
```

```{r}
gen
```

